export const BookingTypes = {
    SET_SELECTED_DATE: 'SET_SELECTED_DATE',
    SET_DID_SELECT_DAY: 'SET_DID_SELECT_DAY',
    SET_SELECTED_SERVICE: 'SET_SELECTED_SERVICE',
    SET_SERVICE_DURATION: 'SET_SERVICE_DURATION',
    SET_DID_SELECT_SERVICE: 'SET_DID_SELECT_SERVICE',
    SET_SELECTED_TIME: 'SET_SELECTED_TIME',
    SET_DID_SELECT_TIME: 'SET_DID_SELECT_TIME',
    SET_NAME: 'SET_NAME',
    SET_EMAIL: 'SET_EMAIL',
    SET_PHONE: 'SET_PHONE',
    SET_TIME_SLOTS: 'SET_TIME_SLOTS'
}