export const BookingTypes = {
    SET_SELECTED_DATE: 'SET_SELECTED_DATE',
    SET_DID_SELECT_DAY: 'SET_DID_SELECT_DAY',
    SET_SELECTED_SERVICE: 'SET_SELECTED_SERVICE',
    SET_DID_SELECT_SERVICE: 'SET_DID_SELECT_SERVICE'
}